name: Spellcheck
on:
  push:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:
jobs:
  spellcheck:
    name: Check spelling
    runs-on: ubuntu-latest
    steps:
      - name: Clone l10n repository
        uses: actions/checkout@v5
      - name: Install packages
        run: |
          sudo apt update
          sudo apt install -y python-dev-is-python3 libhunspell-dev
      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          version: "0.8.11"
      - name: Run checks
        run: |
          ./scripts/update_tmx.sh
          ./scripts/check_strings.sh
