name: Spellcheck
on:
  push:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:
jobs:
  spellcheck:
    name: Check spelling
    runs-on: ubuntu-latest
    steps:
      - name: Clone l10n repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install packages
        run: |
          sudo apt update
          sudo apt install -y python-dev-is-python3 libhunspell-dev
      - name: Set up Python 3
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: '3.12'
      - name: Set up uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          enable-cache: true
          version: "0.8.11"
      - name: Run checks
        run: |
          ./scripts/update_tmx.sh
          ./scripts/check_strings.sh
