name: Spellcheck
on:
  push:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:
jobs:
  spellcheck:
    name: Check spelling
    runs-on: ubuntu-latest
    steps:
      - name: Clone l10n repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Install packages
        run: |
          sudo apt update
          sudo apt install -y python-dev-is-python3 libhunspell-dev
      - name: Set up Python 3
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: '3.12'
      - name: Set up uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
        with:
          enable-cache: true
          version: "0.8.11"
      - name: Run checks
        run: |
          ./scripts/update_tmx.sh
          ./scripts/check_strings.sh
