name: Spellcheck
on:
  schedule:
    - cron: '0 5 * * 1-5' # Run Mon-Fri at 7AM UTC
  workflow_dispatch:
jobs:
  spellcheck:
    name: Check spelling
    runs-on: ubuntu-latest
    steps:
      - name: Clone l10n repository
        uses: actions/checkout@v3
      - name: Set up Python 3
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Run checks
        run: |
          ./scripts/update_tmx.sh
          ./scripts/check_strings.sh
      - run : git config --global user.email 'flodolo@users.noreply.github.com'
      - uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "Update exceptions"
          branch: automation
          delete-branch: true
          title: "Update exceptions"
